# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on:
  push:
    branches-ignore:
      - 'main'
  pull_request: ~

jobs:
  linux:
    name: "CI"
    strategy:
      fail-fast: false
      matrix:
        ci:
        # Use the last stable releases to run more tests
        - { tag: pg15-geos311-gdal35-proj90, mode: coverage }
        - { tag: pg15-clang-geos311-gdal35-proj90, mode: usan_clang }
        # - { tag: pg13-geos39-gdal31-proj71, mode: garden }
        - { tag: pg14-geos39-gdal33-proj71, mode: tests }
        # - { tag: pg14-clang-geos39-gdal33-proj71, mode: usan_clang }
        #- { tag: pg13-geos39-gdal31-proj71, mode: tests }
        #- { tag: pg13-geos39-gdal31-proj71, mode: coverage }
        - { tag: pg13-geos39-gdal31-proj71, mode: usan_gcc }
        - { tag: pg13-clang-geos39-gdal31-proj71, mode: usan_clang }
        # Run tests with different dependency combinations
        - { tag: latest, mode: coverage }
        - { tag: pg13-geos38-gdal31-proj71, mode: tests }
        - { tag: pg12-geos37-gdal30-proj611, mode: tests }

    runs-on: ubuntu-latest
    steps:

    # - name: 'Install Docker'
    #   run: |
    #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    #     sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    #     sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Prepare Image'
      run: |
        set -e
        uname -a
        echo "FROM postgis/postgis-build-env:${{ matrix.ci.tag }}" > Dockerfile
        echo "ADD --chown=postgres:postgres . /src/postgis" >> Dockerfile
        echo "CMD bash ci/github/run_${{ matrix.ci.mode }}.sh" >> Dockerfile
        docker build -t pgtest .

    - name: 'Build & Test'
      run: |
        echo "/tmp/logbt-coredumps/core.%p.%E" | sudo tee /proc/sys/kernel/core_pattern
        ci_env=`bash .github/codecov_env.bash`
        docker run $ci_env --name pgtest-${GITHUB_RUN_NUMBER} pgtest

    - name: 'Clean Up Image'
      if: ${{ success() }}
      run: |
        docker rm pgtest-${GITHUB_RUN_NUMBER}


